import { DiceSource, OpposedContestResult } from "./types";
import { rollSimple } from "./simpleRoll";

/**
 * Roll one opposed contest frame.
 *
 * This intentionally stops before resolving a one-sided optional Edge or
 * starting nested Risk contests. Those decisions belong to the higher-level
 * opposed-roll state machine that will consume skill sequences in later
 * contest frames.
 */
export function rollOpposedContest(
  aSkill: number,
  bSkill: number,
  aDice: DiceSource,
  bDice: DiceSource,
): OpposedContestResult {
  const a = rollSimple(aSkill, aDice);
  const b = rollSimple(bSkill, bDice);

  // A normal Risk generated by a side is Risk against the opponent.
  let riskAgainstA = b.pendingRisk;
  let riskAgainstB = a.pendingRisk;

  // A side that has already fumbled does not need a new pending Risk contest.
  if (a.fumbleSeverity !== null) {
    riskAgainstA = false;
  }
  if (b.fumbleSeverity !== null) {
    riskAgainstB = false;
  }

  const aCanUseEdge = a.edgeAvailable && a.fumbleSeverity === null;
  const bCanUseEdge = b.edgeAvailable && b.fumbleSeverity === null;
  const bothHaveEdge = aCanUseEdge && bCanUseEdge;

  let oneSidedEdgeDecision: OpposedContestResult["oneSidedEdgeDecision"] = null;

  if (bothHaveEdge) {
    // Both sides having Edge in the same contest is automatic double Risk.
    if (a.fumbleSeverity === null) {
      riskAgainstA = true;
    }
    if (b.fumbleSeverity === null) {
      riskAgainstB = true;
    }
  } else if (aCanUseEdge) {
    oneSidedEdgeDecision = { sideWithEdge: "A", target: "B" };
  } else if (bCanUseEdge) {
    oneSidedEdgeDecision = { sideWithEdge: "B", target: "A" };
  }

  return {
    a,
    b,
    riskAgainstA,
    riskAgainstB,
    bothHaveEdge,
    oneSidedEdgeDecision,
  };
}
